apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ob-ingress

spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: 
              number: 80