{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
{{ template "lib-chart.metadata" . }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .type }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .port }}
  {{- end }}
{{- end }}